-- AlterEnum
-- Add new values to EventType enum
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'REST';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'LB_GYM';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'UB_GYM';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'PRE_ACTIVATION';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'REHAB';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'STAFF_MEETING';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'VIDEO_ANALYSIS';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'DAY_OFF';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TRAVEL';

